version: 1.0.{build}
image: Visual Studio 2017
install:
  - npm install -g gulp
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1 -Target CI
test: off
deploy:
- provider: AzureAppServiceZipDeploy
  website: curltocsharp
  username: CurlToCSharp
  password:
    secure: anNXyv5QGtXmsPV21/COiAolYBhLYF8Pi3yWd/qIRd4=
cache:
  - packages
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.nuget\packages
  - tools
